# Generated by Django 3.2.3 on 2021-05-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_image', models.FileField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='max_way.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='_max_way_product_foods_+', to='max_way.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='all_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.AddField(
            model_name='product',
            name='min_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='max_way.minimage'),
        ),
    ]
