# Generated by Django 3.2.3 on 2021-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0002_auto_20210528_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
